version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2023!
      MONGO_INITDB_DATABASE: userDB
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/:/data/db
      - ./data/init/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

networks: 
    app-network:
      name: external-network
      external: true